// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: ff051dd8a6
// Version Date: Sun 15 Mar 23:19:53 UTC 2020

// Package grpc provides a gRPC client for the TEST service.
package grpc

import (
	"context"
	"github.com/pkg/errors"
	"google.golang.org/grpc"
	"google.golang.org/grpc/metadata"

	"github.com/go-kit/kit/endpoint"
	grpctransport "github.com/go-kit/kit/transport/grpc"

	// This Service
	pb "github.com/metaverse/truss/cmd/_integration-tests/server/test-service-definitions/0-basic"
	"github.com/metaverse/truss/cmd/_integration-tests/server/test-service-definitions/0-basic/test-service/svc"
)

// New returns an service backed by a gRPC client connection. It is the
// responsibility of the caller to dial, and later close, the connection.
func New(conn *grpc.ClientConn, options ...ClientOption) (pb.TESTServer, error) {
	var cc clientConfig

	for _, f := range options {
		err := f(&cc)
		if err != nil {
			return nil, errors.Wrap(err, "cannot apply option")
		}
	}

	clientOptions := []grpctransport.ClientOption{
		grpctransport.ClientBefore(
			contextValuesToGRPCMetadata(cc.headers)),
	}
	var getbasicEndpoint endpoint.Endpoint
	{
		getbasicEndpoint = grpctransport.NewClient(
			conn,
			"basic.TEST",
			"GetBasic",
			EncodeGRPCGetBasicRequest,
			DecodeGRPCGetBasicResponse,
			pb.BasicTypeResponse{},
			clientOptions...,
		).Endpoint()
	}

	var postbasicEndpoint endpoint.Endpoint
	{
		postbasicEndpoint = grpctransport.NewClient(
			conn,
			"basic.TEST",
			"PostBasic",
			EncodeGRPCPostBasicRequest,
			DecodeGRPCPostBasicResponse,
			pb.BasicTypeRequest{},
			clientOptions...,
		).Endpoint()
	}

	return svc.Endpoints{
		GetBasicEndpoint:  getbasicEndpoint,
		PostBasicEndpoint: postbasicEndpoint,
	}, nil
}

// GRPC Client Decode

// DecodeGRPCGetBasicResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC getbasic reply to a user-domain getbasic response. Primarily useful in a client.
func DecodeGRPCGetBasicResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.BasicTypeResponse)
	return reply, nil
}

// DecodeGRPCPostBasicResponse is a transport/grpc.DecodeResponseFunc that converts a
// gRPC postbasic reply to a user-domain postbasic response. Primarily useful in a client.
func DecodeGRPCPostBasicResponse(_ context.Context, grpcReply interface{}) (interface{}, error) {
	reply := grpcReply.(*pb.BasicTypeRequest)
	return reply, nil
}

// GRPC Client Encode

// EncodeGRPCGetBasicRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain getbasic request to a gRPC getbasic request. Primarily useful in a client.
func EncodeGRPCGetBasicRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.BasicTypeRequest)
	return req, nil
}

// EncodeGRPCPostBasicRequest is a transport/grpc.EncodeRequestFunc that converts a
// user-domain postbasic request to a gRPC postbasic request. Primarily useful in a client.
func EncodeGRPCPostBasicRequest(_ context.Context, request interface{}) (interface{}, error) {
	req := request.(*pb.BasicTypeRequest)
	return req, nil
}

type clientConfig struct {
	headers []string
}

// ClientOption is a function that modifies the client config
type ClientOption func(*clientConfig) error

func CtxValuesToSend(keys ...string) ClientOption {
	return func(o *clientConfig) error {
		o.headers = keys
		return nil
	}
}

func contextValuesToGRPCMetadata(keys []string) grpctransport.ClientRequestFunc {
	return func(ctx context.Context, md *metadata.MD) context.Context {
		var pairs []string
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				pairs = append(pairs, k, v)
			}
		}

		if pairs != nil {
			*md = metadata.Join(*md, metadata.Pairs(pairs...))
		}

		return ctx
	}
}
